import type { NodeDefinition } from "@/types"

export const NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: "trigger.manual",
    label: "Manual Trigger",
    description: "Start the workflow manually by clicking a button",
    icon: "MousePointerClick",
    color: "#f97316",
    category: "triggers",
    inputs: 0,
    outputs: 1,
    tags: ["trigger", "manual"],
    configSchema: [],
  },
  {
    type: "trigger.webhook",
    label: "Webhook Trigger",
    description: "Receive data from external services via HTTP webhook",
    icon: "Webhook",
    color: "#f97316",
    category: "triggers",
    inputs: 0,
    outputs: 1,
    tags: ["trigger", "webhook", "http"],
    configSchema: [
      { key: "method", label: "HTTP Method", type: "select", options: [
        { label: "POST", value: "POST" },
        { label: "GET", value: "GET" },
        { label: "PUT", value: "PUT" },
        { label: "PATCH", value: "PATCH" },
        { label: "DELETE", value: "DELETE" },
      ], default: "POST" },
      { key: "path", label: "Webhook Path", type: "string", placeholder: "auto-generated" },
      { key: "responseMode", label: "Response Mode", type: "select", options: [
        { label: "Immediately", value: "immediately" },
        { label: "After workflow completes", value: "lastNode" },
      ], default: "immediately" },
    ],
  },
  {
    type: "trigger.schedule",
    label: "Schedule Trigger",
    description: "Run the workflow on a schedule using cron expressions",
    icon: "CalendarClock",
    color: "#f97316",
    category: "triggers",
    inputs: 0,
    outputs: 1,
    tags: ["trigger", "cron", "schedule"],
    configSchema: [
      { key: "cronExpression", label: "Cron Expression", type: "string", placeholder: "0 * * * *", required: true },
      { key: "timezone", label: "Timezone", type: "string", placeholder: "UTC", default: "UTC" },
    ],
  },
  {
    type: "action.http",
    label: "HTTP Request",
    description: "Make HTTP requests to any REST API or URL",
    icon: "Globe",
    color: "#3b82f6",
    category: "core",
    inputs: 1,
    outputs: 1,
    tags: ["http", "rest", "api", "request"],
    configSchema: [
      { key: "url", label: "URL", type: "expression", required: true, placeholder: "https://api.example.com/data" },
      { key: "method", label: "Method", type: "select", options: [
        { label: "GET", value: "GET" },
        { label: "POST", value: "POST" },
        { label: "PUT", value: "PUT" },
        { label: "PATCH", value: "PATCH" },
        { label: "DELETE", value: "DELETE" },
      ], default: "GET" },
      { key: "headers", label: "Headers", type: "json", placeholder: '{"Authorization": "Bearer ..."}' },
      { key: "body", label: "Body", type: "json" },
      { key: "authentication", label: "Authentication", type: "select", options: [
        { label: "None", value: "none" },
        { label: "Bearer Token", value: "bearer" },
        { label: "Basic Auth", value: "basic" },
        { label: "API Key", value: "apiKey" },
      ], default: "none" },
    ],
  },
  {
    type: "action.code",
    label: "Code",
    description: "Run custom JavaScript code to transform or process data",
    icon: "Code2",
    color: "#8b5cf6",
    category: "core",
    inputs: 1,
    outputs: 1,
    tags: ["code", "javascript", "transform", "custom"],
    configSchema: [
      { key: "code", label: "JavaScript Code", type: "code", required: true, default: "// $input contains the input data\n// return the output data\nreturn $input.all();" },
    ],
  },
  {
    type: "action.set",
    label: "Edit Fields",
    description: "Add, edit, or delete fields in your data",
    icon: "Sliders",
    color: "#8b5cf6",
    category: "core",
    inputs: 1,
    outputs: 1,
    tags: ["set", "transform", "fields", "data"],
    configSchema: [
      { key: "assignments", label: "Field Assignments", type: "json", default: [] },
      { key: "mode", label: "Mode", type: "select", options: [
        { label: "Add/Overwrite Fields", value: "addOverwrite" },
        { label: "Keep All Fields", value: "keepAll" },
        { label: "Replace All", value: "replaceAll" },
      ], default: "addOverwrite" },
    ],
  },
  {
    type: "logic.if",
    label: "If Condition",
    description: "Route workflow based on a condition (true/false)",
    icon: "GitBranch",
    color: "#ec4899",
    category: "logic",
    inputs: 1,
    outputs: 2,
    tags: ["if", "condition", "branch", "logic"],
    configSchema: [
      { key: "conditions", label: "Conditions", type: "json", required: true, default: [] },
      { key: "combineOperation", label: "Combine Conditions", type: "select", options: [
        { label: "ALL (AND)", value: "all" },
        { label: "ANY (OR)", value: "any" },
      ], default: "all" },
    ],
  },
  {
    type: "logic.switch",
    label: "Switch",
    description: "Route workflow to different branches based on value",
    icon: "ToggleLeft",
    color: "#ec4899",
    category: "logic",
    inputs: 1,
    outputs: 4,
    tags: ["switch", "route", "branch", "logic"],
    configSchema: [
      { key: "value", label: "Value to Switch On", type: "expression", required: true },
      { key: "rules", label: "Rules", type: "json", default: [] },
    ],
  },
  {
    type: "logic.merge",
    label: "Merge",
    description: "Merge data from multiple branches into one",
    icon: "Merge",
    color: "#ec4899",
    category: "logic",
    inputs: 2,
    outputs: 1,
    tags: ["merge", "combine", "join"],
    configSchema: [
      { key: "mode", label: "Merge Mode", type: "select", options: [
        { label: "Append", value: "append" },
        { label: "By Position", value: "position" },
        { label: "By Key", value: "key" },
        { label: "Multiplex", value: "multiplex" },
      ], default: "append" },
    ],
  },
  {
    type: "logic.loop",
    label: "Loop Over Items",
    description: "Process each item individually in a loop",
    icon: "RefreshCw",
    color: "#ec4899",
    category: "logic",
    inputs: 1,
    outputs: 2,
    tags: ["loop", "iterate", "batch", "each"],
    configSchema: [
      { key: "batchSize", label: "Batch Size", type: "number", default: 1 },
    ],
  },
  {
    type: "integration.slack",
    label: "Slack",
    description: "Send messages and interact with Slack workspaces",
    icon: "MessageSquare",
    color: "#4a154b",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["slack", "message", "notification", "chat"],
    configSchema: [
      { key: "credential", label: "Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Send Message", value: "sendMessage" },
        { label: "Send File", value: "sendFile" },
        { label: "Get User", value: "getUser" },
        { label: "Create Channel", value: "createChannel" },
      ], default: "sendMessage" },
      { key: "channel", label: "Channel", type: "expression", required: true, placeholder: "#general" },
      { key: "text", label: "Message Text", type: "expression", placeholder: "Hello from m8m!" },
    ],
  },
  {
    type: "integration.discord",
    label: "Discord",
    description: "Send messages and interact with Discord servers",
    icon: "MessageCircle",
    color: "#5865f2",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["discord", "message", "notification", "chat"],
    configSchema: [
      { key: "webhookUrl", label: "Webhook URL", type: "string", required: true },
      { key: "content", label: "Message Content", type: "expression", required: true },
      { key: "username", label: "Username Override", type: "string" },
      { key: "avatarUrl", label: "Avatar URL", type: "string" },
    ],
  },
  {
    type: "integration.email",
    label: "Send Email",
    description: "Send emails via SMTP",
    icon: "Mail",
    color: "#06b6d4",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["email", "smtp", "send", "notification"],
    configSchema: [
      { key: "credential", label: "SMTP Credential", type: "credential" },
      { key: "to", label: "To", type: "expression", required: true, placeholder: "user@example.com" },
      { key: "subject", label: "Subject", type: "expression", required: true },
      { key: "body", label: "Body", type: "expression", required: true },
      { key: "isHtml", label: "HTML Email", type: "boolean", default: false },
    ],
  },
  {
    type: "integration.github",
    label: "GitHub",
    description: "Interact with GitHub repositories, issues, and PRs",
    icon: "Github",
    color: "#24292f",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["github", "git", "repo", "issue", "pr"],
    configSchema: [
      { key: "credential", label: "GitHub Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Issue", value: "createIssue" },
        { label: "Get Issue", value: "getIssue" },
        { label: "Create PR Comment", value: "createPRComment" },
        { label: "List Repos", value: "listRepos" },
        { label: "Get File Content", value: "getFileContent" },
      ], default: "createIssue" },
      { key: "owner", label: "Owner", type: "expression", required: true },
      { key: "repo", label: "Repository", type: "expression", required: true },
    ],
  },
  {
    type: "integration.notion",
    label: "Notion",
    description: "Read and write Notion pages and databases",
    icon: "BookOpen",
    color: "#000000",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["notion", "database", "pages", "notes"],
    configSchema: [
      { key: "credential", label: "Notion Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Page", value: "createPage" },
        { label: "Update Page", value: "updatePage" },
        { label: "Get Page", value: "getPage" },
        { label: "Query Database", value: "queryDatabase" },
      ], default: "createPage" },
    ],
  },
  {
    type: "integration.openai",
    label: "OpenAI / AI",
    description: "Use GPT models for text generation, analysis, and more",
    icon: "Sparkles",
    color: "#10a37f",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["openai", "ai", "gpt", "llm", "generate"],
    configSchema: [
      { key: "credential", label: "OpenAI Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Chat Completion", value: "chat" },
        { label: "Text Completion", value: "completion" },
        { label: "Create Embedding", value: "embedding" },
        { label: "Create Image", value: "image" },
      ], default: "chat" },
      { key: "model", label: "Model", type: "select", options: [
        { label: "GPT-4o", value: "gpt-4o" },
        { label: "GPT-4o Mini", value: "gpt-4o-mini" },
        { label: "GPT-4 Turbo", value: "gpt-4-turbo" },
        { label: "GPT-3.5 Turbo", value: "gpt-3.5-turbo" },
      ], default: "gpt-4o-mini" },
      { key: "prompt", label: "Prompt / Message", type: "expression", required: true },
      { key: "systemMessage", label: "System Message", type: "string" },
      { key: "temperature", label: "Temperature", type: "number", default: 0.7 },
    ],
  },
  {
    type: "integration.postgres",
    label: "PostgreSQL",
    description: "Execute queries against a PostgreSQL database",
    icon: "Database",
    color: "#336791",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["postgres", "sql", "database", "query"],
    configSchema: [
      { key: "credential", label: "Postgres Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Execute Query", value: "executeQuery" },
        { label: "Insert", value: "insert" },
        { label: "Update", value: "update" },
        { label: "Delete", value: "delete" },
        { label: "Select", value: "select" },
      ], default: "executeQuery" },
      { key: "query", label: "SQL Query", type: "code", placeholder: "SELECT * FROM users WHERE id = $1" },
    ],
  },
  {
    type: "integration.sheets",
    label: "Google Sheets",
    description: "Read and write data in Google Sheets",
    icon: "Sheet",
    color: "#34a853",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["google", "sheets", "spreadsheet", "data"],
    configSchema: [
      { key: "credential", label: "Google Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Append Row", value: "appendRow" },
        { label: "Read Rows", value: "readRows" },
        { label: "Update Row", value: "updateRow" },
        { label: "Clear Sheet", value: "clearSheet" },
      ], default: "appendRow" },
      { key: "spreadsheetId", label: "Spreadsheet ID", type: "expression", required: true },
      { key: "sheetName", label: "Sheet Name", type: "expression", default: "Sheet1" },
    ],
  },
  {
    type: "integration.telegram",
    label: "Telegram",
    description: "Send messages and files via Telegram Bot API",
    icon: "Send",
    color: "#229ED9",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["telegram", "bot", "message", "notification"],
    configSchema: [
      { key: "credential", label: "Telegram Credential", type: "credential" },
      { key: "chatId", label: "Chat ID", type: "expression", required: true },
      { key: "text", label: "Message Text", type: "expression", required: true },
      { key: "parseMode", label: "Parse Mode", type: "select", options: [
        { label: "Text", value: "text" },
        { label: "Markdown", value: "Markdown" },
        { label: "HTML", value: "HTML" },
      ], default: "text" },
    ],
  },
  {
    type: "integration.stripe",
    label: "Stripe",
    description: "Process payments and interact with the Stripe API",
    icon: "CreditCard",
    color: "#635bff",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["stripe", "payment", "billing", "charge"],
    configSchema: [
      { key: "credential", label: "Stripe Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Payment Intent", value: "createPaymentIntent" },
        { label: "Get Customer", value: "getCustomer" },
        { label: "Create Customer", value: "createCustomer" },
        { label: "List Charges", value: "listCharges" },
        { label: "Get Subscription", value: "getSubscription" },
      ], default: "createPaymentIntent" },
    ],
  },
  {
    type: "integration.whatsapp",
    label: "WhatsApp",
    description: "Send messages, media, and templates via WhatsApp Business API",
    icon: "MessageCircle",
    color: "#25D366",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["whatsapp", "message", "chat", "notification", "meta"],
    configSchema: [
      { key: "credential", label: "WhatsApp Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Send Text Message", value: "sendText" },
        { label: "Send Template Message", value: "sendTemplate" },
        { label: "Send Image", value: "sendImage" },
        { label: "Send Document", value: "sendDocument" },
        { label: "Mark as Read", value: "markRead" },
      ], default: "sendText" },
      { key: "phoneNumber", label: "Phone Number", type: "expression", required: true, placeholder: "+1234567890" },
      { key: "message", label: "Message", type: "expression", placeholder: "Hello from m8m!" },
    ],
  },
  {
    type: "integration.facebook",
    label: "Facebook",
    description: "Post content, manage pages, and interact with Facebook Graph API",
    icon: "Facebook",
    color: "#1877F2",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["facebook", "meta", "social", "post", "page"],
    configSchema: [
      { key: "credential", label: "Facebook Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Post", value: "createPost" },
        { label: "Get Page Posts", value: "getPagePosts" },
        { label: "Get Post Insights", value: "getPostInsights" },
        { label: "Send Message (Messenger)", value: "sendMessage" },
        { label: "Get Page Info", value: "getPageInfo" },
      ], default: "createPost" },
      { key: "pageId", label: "Page ID", type: "expression", required: true },
      { key: "message", label: "Message / Content", type: "expression" },
    ],
  },
  {
    type: "integration.youtube",
    label: "YouTube",
    description: "Upload videos, manage channels, and fetch analytics",
    icon: "Youtube",
    color: "#FF0000",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["youtube", "video", "google", "upload", "channel"],
    configSchema: [
      { key: "credential", label: "YouTube Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Upload Video", value: "uploadVideo" },
        { label: "Get Video Details", value: "getVideo" },
        { label: "List Channel Videos", value: "listVideos" },
        { label: "Get Channel Stats", value: "getChannelStats" },
        { label: "Add Comment", value: "addComment" },
        { label: "Search Videos", value: "searchVideos" },
      ], default: "getVideo" },
      { key: "videoId", label: "Video ID", type: "expression", placeholder: "dQw4w9WgXcQ" },
      { key: "channelId", label: "Channel ID", type: "expression" },
    ],
  },
  {
    type: "integration.twitter",
    label: "Twitter / X",
    description: "Post tweets, read timelines, and interact with the X API",
    icon: "Twitter",
    color: "#000000",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["twitter", "x", "tweet", "social", "post"],
    configSchema: [
      { key: "credential", label: "Twitter Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Post Tweet", value: "postTweet" },
        { label: "Get Tweet", value: "getTweet" },
        { label: "Search Tweets", value: "searchTweets" },
        { label: "Get User Timeline", value: "getUserTimeline" },
        { label: "Like Tweet", value: "likeTweet" },
        { label: "Retweet", value: "retweet" },
      ], default: "postTweet" },
      { key: "text", label: "Tweet Text", type: "expression", placeholder: "Hello from m8m!" },
      { key: "tweetId", label: "Tweet ID", type: "expression" },
    ],
  },
  {
    type: "integration.instagram",
    label: "Instagram",
    description: "Post media, fetch insights, and manage Instagram content",
    icon: "Instagram",
    color: "#E4405F",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["instagram", "meta", "social", "photo", "story"],
    configSchema: [
      { key: "credential", label: "Instagram Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Media Post", value: "createMedia" },
        { label: "Get Media", value: "getMedia" },
        { label: "Get User Profile", value: "getUserProfile" },
        { label: "Get Insights", value: "getInsights" },
        { label: "Get Recent Media", value: "getRecentMedia" },
      ], default: "createMedia" },
      { key: "imageUrl", label: "Image URL", type: "expression" },
      { key: "caption", label: "Caption", type: "expression" },
    ],
  },
  {
    type: "integration.linkedin",
    label: "LinkedIn",
    description: "Post updates, manage profiles, and interact with LinkedIn API",
    icon: "Linkedin",
    color: "#0A66C2",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["linkedin", "social", "professional", "post", "network"],
    configSchema: [
      { key: "credential", label: "LinkedIn Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Post", value: "createPost" },
        { label: "Get Profile", value: "getProfile" },
        { label: "Get Company Updates", value: "getCompanyUpdates" },
        { label: "Send Message", value: "sendMessage" },
      ], default: "createPost" },
      { key: "text", label: "Post Text", type: "expression", placeholder: "Exciting update!" },
    ],
  },
  {
    type: "integration.drive",
    label: "Google Drive",
    description: "Upload, download, and manage files in Google Drive",
    icon: "HardDrive",
    color: "#4285F4",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["google", "drive", "files", "upload", "storage"],
    configSchema: [
      { key: "credential", label: "Google Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Upload File", value: "uploadFile" },
        { label: "Download File", value: "downloadFile" },
        { label: "List Files", value: "listFiles" },
        { label: "Create Folder", value: "createFolder" },
        { label: "Move File", value: "moveFile" },
        { label: "Delete File", value: "deleteFile" },
      ], default: "listFiles" },
      { key: "fileId", label: "File ID", type: "expression" },
      { key: "folderName", label: "Folder Name", type: "expression" },
    ],
  },
  {
    type: "integration.spotify",
    label: "Spotify",
    description: "Search music, manage playlists, and control playback",
    icon: "Music",
    color: "#1DB954",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["spotify", "music", "playlist", "audio", "streaming"],
    configSchema: [
      { key: "credential", label: "Spotify Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Search Tracks", value: "searchTracks" },
        { label: "Get Playlist", value: "getPlaylist" },
        { label: "Add to Playlist", value: "addToPlaylist" },
        { label: "Get Currently Playing", value: "getCurrentlyPlaying" },
        { label: "Get User Top Tracks", value: "getTopTracks" },
      ], default: "searchTracks" },
      { key: "query", label: "Search Query", type: "expression", placeholder: "Artist or track name" },
      { key: "playlistId", label: "Playlist ID", type: "expression" },
    ],
  },
  {
    type: "integration.tiktok",
    label: "TikTok",
    description: "Post videos, get analytics, and interact with TikTok API",
    icon: "Video",
    color: "#000000",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["tiktok", "video", "social", "short", "viral"],
    configSchema: [
      { key: "credential", label: "TikTok Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Get Video Info", value: "getVideoInfo" },
        { label: "Get User Info", value: "getUserInfo" },
        { label: "Get User Videos", value: "getUserVideos" },
        { label: "Search Videos", value: "searchVideos" },
      ], default: "getVideoInfo" },
      { key: "videoId", label: "Video ID", type: "expression" },
      { key: "username", label: "Username", type: "expression" },
    ],
  },
  {
    type: "integration.shopify",
    label: "Shopify",
    description: "Manage products, orders, and customers on Shopify",
    icon: "ShoppingBag",
    color: "#96BF48",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["shopify", "ecommerce", "store", "orders", "products"],
    configSchema: [
      { key: "credential", label: "Shopify Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Product", value: "createProduct" },
        { label: "Get Product", value: "getProduct" },
        { label: "List Orders", value: "listOrders" },
        { label: "Create Order", value: "createOrder" },
        { label: "Get Customer", value: "getCustomer" },
        { label: "Update Inventory", value: "updateInventory" },
      ], default: "listOrders" },
      { key: "productTitle", label: "Product Title", type: "expression" },
      { key: "orderId", label: "Order ID", type: "expression" },
    ],
  },
  {
    type: "integration.twilio",
    label: "Twilio SMS",
    description: "Send and receive SMS messages via Twilio",
    icon: "Phone",
    color: "#F22F46",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["twilio", "sms", "phone", "text", "message"],
    configSchema: [
      { key: "credential", label: "Twilio Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Send SMS", value: "sendSMS" },
        { label: "Send WhatsApp", value: "sendWhatsApp" },
        { label: "Make Call", value: "makeCall" },
        { label: "Get Message", value: "getMessage" },
      ], default: "sendSMS" },
      { key: "to", label: "To Phone Number", type: "expression", required: true, placeholder: "+1234567890" },
      { key: "body", label: "Message Body", type: "expression", required: true },
    ],
  },
  {
    type: "integration.mongodb",
    label: "MongoDB",
    description: "Query and manipulate documents in MongoDB collections",
    icon: "Database",
    color: "#47A248",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["mongodb", "nosql", "database", "document"],
    configSchema: [
      { key: "credential", label: "MongoDB Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Find Documents", value: "find" },
        { label: "Insert Document", value: "insertOne" },
        { label: "Update Document", value: "updateOne" },
        { label: "Delete Document", value: "deleteOne" },
        { label: "Aggregate", value: "aggregate" },
      ], default: "find" },
      { key: "collection", label: "Collection", type: "expression", required: true },
      { key: "filter", label: "Filter (JSON)", type: "json", placeholder: '{"status": "active"}' },
    ],
  },
  {
    type: "integration.s3",
    label: "AWS S3",
    description: "Upload, download, and manage files in Amazon S3 buckets",
    icon: "Cloud",
    color: "#FF9900",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["aws", "s3", "storage", "bucket", "files", "cloud"],
    configSchema: [
      { key: "credential", label: "AWS Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Upload File", value: "putObject" },
        { label: "Download File", value: "getObject" },
        { label: "List Objects", value: "listObjects" },
        { label: "Delete Object", value: "deleteObject" },
        { label: "Create Bucket", value: "createBucket" },
      ], default: "listObjects" },
      { key: "bucket", label: "Bucket Name", type: "expression", required: true },
      { key: "key", label: "Object Key", type: "expression" },
    ],
  },
  {
    type: "integration.firebase",
    label: "Firebase",
    description: "Read and write data in Firebase Firestore and Realtime Database",
    icon: "Flame",
    color: "#FFCA28",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["firebase", "google", "firestore", "realtime", "database"],
    configSchema: [
      { key: "credential", label: "Firebase Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Get Document", value: "getDocument" },
        { label: "Create Document", value: "createDocument" },
        { label: "Update Document", value: "updateDocument" },
        { label: "Delete Document", value: "deleteDocument" },
        { label: "Query Collection", value: "queryCollection" },
      ], default: "getDocument" },
      { key: "collection", label: "Collection Path", type: "expression", required: true },
      { key: "documentId", label: "Document ID", type: "expression" },
    ],
  },
  {
    type: "integration.hubspot",
    label: "HubSpot",
    description: "Manage contacts, deals, and CRM data in HubSpot",
    icon: "Users",
    color: "#FF7A59",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["hubspot", "crm", "contacts", "deals", "marketing"],
    configSchema: [
      { key: "credential", label: "HubSpot Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Contact", value: "createContact" },
        { label: "Get Contact", value: "getContact" },
        { label: "Create Deal", value: "createDeal" },
        { label: "List Contacts", value: "listContacts" },
        { label: "Update Contact", value: "updateContact" },
      ], default: "createContact" },
      { key: "email", label: "Contact Email", type: "expression" },
      { key: "properties", label: "Properties (JSON)", type: "json" },
    ],
  },
  {
    type: "integration.airtable",
    label: "Airtable",
    description: "Read, create, and update records in Airtable bases",
    icon: "Table",
    color: "#18BFFF",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["airtable", "database", "spreadsheet", "records"],
    configSchema: [
      { key: "credential", label: "Airtable Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "List Records", value: "listRecords" },
        { label: "Create Record", value: "createRecord" },
        { label: "Update Record", value: "updateRecord" },
        { label: "Delete Record", value: "deleteRecord" },
        { label: "Search Records", value: "searchRecords" },
      ], default: "listRecords" },
      { key: "baseId", label: "Base ID", type: "expression", required: true },
      { key: "tableName", label: "Table Name", type: "expression", required: true },
    ],
  },
  {
    type: "integration.zoom",
    label: "Zoom",
    description: "Create meetings, manage recordings, and interact with Zoom",
    icon: "Video",
    color: "#2D8CFF",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["zoom", "meeting", "video", "call", "conference"],
    configSchema: [
      { key: "credential", label: "Zoom Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Meeting", value: "createMeeting" },
        { label: "Get Meeting", value: "getMeeting" },
        { label: "List Meetings", value: "listMeetings" },
        { label: "Delete Meeting", value: "deleteMeeting" },
        { label: "List Recordings", value: "listRecordings" },
      ], default: "createMeeting" },
      { key: "topic", label: "Meeting Topic", type: "expression" },
      { key: "duration", label: "Duration (minutes)", type: "number", default: 30 },
    ],
  },
  {
    type: "integration.calendly",
    label: "Calendly",
    description: "Manage scheduling events and invitees with Calendly",
    icon: "Calendar",
    color: "#006BFF",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["calendly", "scheduling", "calendar", "booking"],
    configSchema: [
      { key: "credential", label: "Calendly Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "List Events", value: "listEvents" },
        { label: "Get Event", value: "getEvent" },
        { label: "List Invitees", value: "listInvitees" },
        { label: "Cancel Event", value: "cancelEvent" },
      ], default: "listEvents" },
    ],
  },
  {
    type: "integration.jira",
    label: "Jira",
    description: "Create and manage issues, projects, and sprints in Jira",
    icon: "ClipboardList",
    color: "#0052CC",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["jira", "project", "issues", "agile", "atlassian"],
    configSchema: [
      { key: "credential", label: "Jira Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Issue", value: "createIssue" },
        { label: "Get Issue", value: "getIssue" },
        { label: "Update Issue", value: "updateIssue" },
        { label: "Add Comment", value: "addComment" },
        { label: "Transition Issue", value: "transitionIssue" },
      ], default: "createIssue" },
      { key: "projectKey", label: "Project Key", type: "expression", required: true },
      { key: "summary", label: "Summary", type: "expression" },
      { key: "issueType", label: "Issue Type", type: "select", options: [
        { label: "Bug", value: "Bug" },
        { label: "Task", value: "Task" },
        { label: "Story", value: "Story" },
        { label: "Epic", value: "Epic" },
      ], default: "Task" },
    ],
  },
  {
    type: "integration.mailchimp",
    label: "Mailchimp",
    description: "Manage email campaigns, lists, and subscribers",
    icon: "Mail",
    color: "#FFE01B",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["mailchimp", "email", "marketing", "newsletter", "campaign"],
    configSchema: [
      { key: "credential", label: "Mailchimp Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Add Subscriber", value: "addSubscriber" },
        { label: "Remove Subscriber", value: "removeSubscriber" },
        { label: "Create Campaign", value: "createCampaign" },
        { label: "Send Campaign", value: "sendCampaign" },
        { label: "Get List Members", value: "getListMembers" },
      ], default: "addSubscriber" },
      { key: "listId", label: "List/Audience ID", type: "expression", required: true },
      { key: "email", label: "Email Address", type: "expression" },
    ],
  },
  {
    type: "integration.dropbox",
    label: "Dropbox",
    description: "Upload, download, and manage files in Dropbox",
    icon: "Cloud",
    color: "#0061FF",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["dropbox", "files", "storage", "cloud", "sync"],
    configSchema: [
      { key: "credential", label: "Dropbox Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Upload File", value: "uploadFile" },
        { label: "Download File", value: "downloadFile" },
        { label: "List Files", value: "listFiles" },
        { label: "Create Folder", value: "createFolder" },
        { label: "Delete File", value: "deleteFile" },
        { label: "Get File Metadata", value: "getMetadata" },
      ], default: "listFiles" },
      { key: "path", label: "File Path", type: "expression", placeholder: "/folder/file.txt" },
    ],
  },
  {
    type: "integration.redis",
    label: "Redis",
    description: "Get, set, and manage key-value data in Redis",
    icon: "Database",
    color: "#DC382D",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["redis", "cache", "key-value", "database"],
    configSchema: [
      { key: "credential", label: "Redis Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Get", value: "get" },
        { label: "Set", value: "set" },
        { label: "Delete", value: "delete" },
        { label: "Get All Keys", value: "keys" },
        { label: "Increment", value: "incr" },
        { label: "Publish", value: "publish" },
      ], default: "get" },
      { key: "key", label: "Key", type: "expression", required: true },
      { key: "value", label: "Value", type: "expression" },
    ],
  },
  {
    type: "integration.openrouter",
    label: "OpenRouter AI",
    description: "Access multiple AI models via OpenRouter (Claude, Llama, Mistral, etc.)",
    icon: "Sparkles",
    color: "#6366f1",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["openrouter", "ai", "llm", "claude", "llama", "mistral"],
    configSchema: [
      { key: "credential", label: "OpenRouter Credential", type: "credential" },
      { key: "model", label: "Model", type: "select", options: [
        { label: "Claude 3.5 Sonnet", value: "anthropic/claude-3.5-sonnet" },
        { label: "GPT-4o", value: "openai/gpt-4o" },
        { label: "Llama 3.1 70B", value: "meta-llama/llama-3.1-70b" },
        { label: "Mistral Large", value: "mistralai/mistral-large" },
        { label: "Gemini Pro", value: "google/gemini-pro" },
      ], default: "anthropic/claude-3.5-sonnet" },
      { key: "prompt", label: "Prompt", type: "expression", required: true },
      { key: "systemMessage", label: "System Message", type: "string" },
      { key: "temperature", label: "Temperature", type: "number", default: 0.7 },
    ],
  },
  {
    type: "integration.supabase",
    label: "Supabase",
    description: "Query tables, manage auth, and use realtime features in Supabase",
    icon: "Database",
    color: "#3ECF8E",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["supabase", "database", "postgres", "auth", "realtime"],
    configSchema: [
      { key: "credential", label: "Supabase Credential", type: "credential" },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Select Rows", value: "select" },
        { label: "Insert Row", value: "insert" },
        { label: "Update Row", value: "update" },
        { label: "Delete Row", value: "delete" },
        { label: "Call Function (RPC)", value: "rpc" },
      ], default: "select" },
      { key: "table", label: "Table Name", type: "expression", required: true },
      { key: "filter", label: "Filter", type: "json" },
    ],
  },
]

export const NODE_CATEGORIES: { id: string; label: string; color: string }[] = [
  { id: "triggers", label: "Triggers", color: "#f97316" },
  { id: "core", label: "Core", color: "#3b82f6" },
  { id: "logic", label: "Logic", color: "#ec4899" },
  { id: "integrations", label: "Integrations", color: "#8b5cf6" },
]

export function getNodeDefinition(type: string): NodeDefinition | undefined {
  return NODE_DEFINITIONS.find((n) => n.type === type)
}

export function getNodesByCategory(category: string): NodeDefinition[] {
  return NODE_DEFINITIONS.filter((n) => n.category === category)
}
