import type { NodeDefinition } from "@/types"

export const NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: "trigger.manual",
    label: "Manual Trigger",
    description: "Start the workflow manually by clicking a button",
    icon: "MousePointerClick",
    color: "#f97316",
    category: "triggers",
    inputs: 0,
    outputs: 1,
    tags: ["trigger", "manual"],
    configSchema: [],
  },
  {
    type: "trigger.webhook",
    label: "Webhook Trigger",
    description: "Receive data from external services via HTTP webhook",
    icon: "Webhook",
    color: "#f97316",
    category: "triggers",
    inputs: 0,
    outputs: 1,
    tags: ["trigger", "webhook", "http"],
    configSchema: [
      { key: "method", label: "HTTP Method", type: "select", options: [
        { label: "POST", value: "POST" },
        { label: "GET", value: "GET" },
        { label: "PUT", value: "PUT" },
        { label: "PATCH", value: "PATCH" },
        { label: "DELETE", value: "DELETE" },
      ], default: "POST" },
      { key: "path", label: "Webhook Path", type: "string", placeholder: "auto-generated" },
      { key: "responseMode", label: "Response Mode", type: "select", options: [
        { label: "Immediately", value: "immediately" },
        { label: "After workflow completes", value: "lastNode" },
      ], default: "immediately" },
    ],
  },
  {
    type: "trigger.schedule",
    label: "Schedule Trigger",
    description: "Run the workflow on a schedule using cron expressions",
    icon: "CalendarClock",
    color: "#f97316",
    category: "triggers",
    inputs: 0,
    outputs: 1,
    tags: ["trigger", "cron", "schedule"],
    configSchema: [
      { key: "cronExpression", label: "Cron Expression", type: "string", placeholder: "0 * * * *", required: true },
      { key: "timezone", label: "Timezone", type: "string", placeholder: "UTC", default: "UTC" },
    ],
  },
  {
    type: "action.http",
    label: "HTTP Request",
    description: "Make HTTP requests to any REST API or URL",
    icon: "Globe",
    color: "#3b82f6",
    category: "core",
    inputs: 1,
    outputs: 1,
    tags: ["http", "rest", "api", "request"],
    configSchema: [
      { key: "url", label: "URL", type: "expression", required: true, placeholder: "https://api.example.com/data" },
      { key: "method", label: "Method", type: "select", options: [
        { label: "GET", value: "GET" },
        { label: "POST", value: "POST" },
        { label: "PUT", value: "PUT" },
        { label: "PATCH", value: "PATCH" },
        { label: "DELETE", value: "DELETE" },
      ], default: "GET" },
      { key: "headers", label: "Headers", type: "json", placeholder: '{"Authorization": "Bearer ..."}' },
      { key: "body", label: "Body", type: "json" },
      { key: "authentication", label: "Authentication", type: "select", options: [
        { label: "None", value: "none" },
        { label: "Bearer Token", value: "bearer" },
        { label: "Basic Auth", value: "basic" },
        { label: "API Key", value: "apiKey" },
      ], default: "none" },
    ],
  },
  {
    type: "action.code",
    label: "Code",
    description: "Run custom JavaScript code to transform or process data",
    icon: "Code2",
    color: "#8b5cf6",
    category: "core",
    inputs: 1,
    outputs: 1,
    tags: ["code", "javascript", "transform", "custom"],
    configSchema: [
      { key: "code", label: "JavaScript Code", type: "code", required: true, default: "// $input contains the input data\n// return the output data\nreturn $input.all();" },
    ],
  },
  {
    type: "action.set",
    label: "Edit Fields",
    description: "Add, edit, or delete fields in your data",
    icon: "Sliders",
    color: "#8b5cf6",
    category: "core",
    inputs: 1,
    outputs: 1,
    tags: ["set", "transform", "fields", "data"],
    configSchema: [
      { key: "assignments", label: "Field Assignments", type: "json", default: [] },
      { key: "mode", label: "Mode", type: "select", options: [
        { label: "Add/Overwrite Fields", value: "addOverwrite" },
        { label: "Keep All Fields", value: "keepAll" },
        { label: "Replace All", value: "replaceAll" },
      ], default: "addOverwrite" },
    ],
  },
  {
    type: "logic.if",
    label: "If Condition",
    description: "Route workflow based on a condition (true/false)",
    icon: "GitBranch",
    color: "#ec4899",
    category: "logic",
    inputs: 1,
    outputs: 2,
    tags: ["if", "condition", "branch", "logic"],
    configSchema: [
      { key: "conditions", label: "Conditions", type: "json", required: true, default: [] },
      { key: "combineOperation", label: "Combine Conditions", type: "select", options: [
        { label: "ALL (AND)", value: "all" },
        { label: "ANY (OR)", value: "any" },
      ], default: "all" },
    ],
  },
  {
    type: "logic.switch",
    label: "Switch",
    description: "Route workflow to different branches based on value",
    icon: "ToggleLeft",
    color: "#ec4899",
    category: "logic",
    inputs: 1,
    outputs: 4,
    tags: ["switch", "route", "branch", "logic"],
    configSchema: [
      { key: "value", label: "Value to Switch On", type: "expression", required: true },
      { key: "rules", label: "Rules", type: "json", default: [] },
    ],
  },
  {
    type: "logic.merge",
    label: "Merge",
    description: "Merge data from multiple branches into one",
    icon: "Merge",
    color: "#ec4899",
    category: "logic",
    inputs: 2,
    outputs: 1,
    tags: ["merge", "combine", "join"],
    configSchema: [
      { key: "mode", label: "Merge Mode", type: "select", options: [
        { label: "Append", value: "append" },
        { label: "By Position", value: "position" },
        { label: "By Key", value: "key" },
        { label: "Multiplex", value: "multiplex" },
      ], default: "append" },
    ],
  },
  {
    type: "logic.loop",
    label: "Loop Over Items",
    description: "Process each item individually in a loop",
    icon: "RefreshCw",
    color: "#ec4899",
    category: "logic",
    inputs: 1,
    outputs: 2,
    tags: ["loop", "iterate", "batch", "each"],
    configSchema: [
      { key: "batchSize", label: "Batch Size", type: "number", default: 1 },
    ],
  },
  {
    type: "integration.slack",
    label: "Slack",
    description: "Send messages and interact with Slack workspaces",
    icon: "MessageSquare",
    color: "#4a154b",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["slack", "message", "notification", "chat"],
    configSchema: [
      { key: "credential", label: "Credential", type: "credential", required: true },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Send Message", value: "sendMessage" },
        { label: "Send File", value: "sendFile" },
        { label: "Get User", value: "getUser" },
        { label: "Create Channel", value: "createChannel" },
      ], default: "sendMessage" },
      { key: "channel", label: "Channel", type: "expression", required: true, placeholder: "#general" },
      { key: "text", label: "Message Text", type: "expression", placeholder: "Hello from m8m!" },
    ],
  },
  {
    type: "integration.discord",
    label: "Discord",
    description: "Send messages and interact with Discord servers",
    icon: "MessageCircle",
    color: "#5865f2",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["discord", "message", "notification", "chat"],
    configSchema: [
      { key: "webhookUrl", label: "Webhook URL", type: "string", required: true },
      { key: "content", label: "Message Content", type: "expression", required: true },
      { key: "username", label: "Username Override", type: "string" },
      { key: "avatarUrl", label: "Avatar URL", type: "string" },
    ],
  },
  {
    type: "integration.email",
    label: "Send Email",
    description: "Send emails via SMTP",
    icon: "Mail",
    color: "#06b6d4",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["email", "smtp", "send", "notification"],
    configSchema: [
      { key: "credential", label: "SMTP Credential", type: "credential", required: true },
      { key: "to", label: "To", type: "expression", required: true, placeholder: "user@example.com" },
      { key: "subject", label: "Subject", type: "expression", required: true },
      { key: "body", label: "Body", type: "expression", required: true },
      { key: "isHtml", label: "HTML Email", type: "boolean", default: false },
    ],
  },
  {
    type: "integration.github",
    label: "GitHub",
    description: "Interact with GitHub repositories, issues, and PRs",
    icon: "Github",
    color: "#24292f",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["github", "git", "repo", "issue", "pr"],
    configSchema: [
      { key: "credential", label: "GitHub Credential", type: "credential", required: true },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Issue", value: "createIssue" },
        { label: "Get Issue", value: "getIssue" },
        { label: "Create PR Comment", value: "createPRComment" },
        { label: "List Repos", value: "listRepos" },
        { label: "Get File Content", value: "getFileContent" },
      ], default: "createIssue" },
      { key: "owner", label: "Owner", type: "expression", required: true },
      { key: "repo", label: "Repository", type: "expression", required: true },
    ],
  },
  {
    type: "integration.notion",
    label: "Notion",
    description: "Read and write Notion pages and databases",
    icon: "BookOpen",
    color: "#000000",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["notion", "database", "pages", "notes"],
    configSchema: [
      { key: "credential", label: "Notion Credential", type: "credential", required: true },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Page", value: "createPage" },
        { label: "Update Page", value: "updatePage" },
        { label: "Get Page", value: "getPage" },
        { label: "Query Database", value: "queryDatabase" },
      ], default: "createPage" },
    ],
  },
  {
    type: "integration.openai",
    label: "OpenAI / AI",
    description: "Use GPT models for text generation, analysis, and more",
    icon: "Sparkles",
    color: "#10a37f",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["openai", "ai", "gpt", "llm", "generate"],
    configSchema: [
      { key: "credential", label: "OpenAI Credential", type: "credential", required: true },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Chat Completion", value: "chat" },
        { label: "Text Completion", value: "completion" },
        { label: "Create Embedding", value: "embedding" },
        { label: "Create Image", value: "image" },
      ], default: "chat" },
      { key: "model", label: "Model", type: "select", options: [
        { label: "GPT-4o", value: "gpt-4o" },
        { label: "GPT-4o Mini", value: "gpt-4o-mini" },
        { label: "GPT-4 Turbo", value: "gpt-4-turbo" },
        { label: "GPT-3.5 Turbo", value: "gpt-3.5-turbo" },
      ], default: "gpt-4o-mini" },
      { key: "prompt", label: "Prompt / Message", type: "expression", required: true },
      { key: "systemMessage", label: "System Message", type: "string" },
      { key: "temperature", label: "Temperature", type: "number", default: 0.7 },
    ],
  },
  {
    type: "integration.postgres",
    label: "PostgreSQL",
    description: "Execute queries against a PostgreSQL database",
    icon: "Database",
    color: "#336791",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["postgres", "sql", "database", "query"],
    configSchema: [
      { key: "credential", label: "Postgres Credential", type: "credential", required: true },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Execute Query", value: "executeQuery" },
        { label: "Insert", value: "insert" },
        { label: "Update", value: "update" },
        { label: "Delete", value: "delete" },
        { label: "Select", value: "select" },
      ], default: "executeQuery" },
      { key: "query", label: "SQL Query", type: "code", placeholder: "SELECT * FROM users WHERE id = $1" },
    ],
  },
  {
    type: "integration.sheets",
    label: "Google Sheets",
    description: "Read and write data in Google Sheets",
    icon: "Sheet",
    color: "#34a853",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["google", "sheets", "spreadsheet", "data"],
    configSchema: [
      { key: "credential", label: "Google Credential", type: "credential", required: true },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Append Row", value: "appendRow" },
        { label: "Read Rows", value: "readRows" },
        { label: "Update Row", value: "updateRow" },
        { label: "Clear Sheet", value: "clearSheet" },
      ], default: "appendRow" },
      { key: "spreadsheetId", label: "Spreadsheet ID", type: "expression", required: true },
      { key: "sheetName", label: "Sheet Name", type: "expression", default: "Sheet1" },
    ],
  },
  {
    type: "integration.telegram",
    label: "Telegram",
    description: "Send messages and files via Telegram Bot API",
    icon: "Send",
    color: "#229ED9",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["telegram", "bot", "message", "notification"],
    configSchema: [
      { key: "credential", label: "Telegram Credential", type: "credential", required: true },
      { key: "chatId", label: "Chat ID", type: "expression", required: true },
      { key: "text", label: "Message Text", type: "expression", required: true },
      { key: "parseMode", label: "Parse Mode", type: "select", options: [
        { label: "Text", value: "text" },
        { label: "Markdown", value: "Markdown" },
        { label: "HTML", value: "HTML" },
      ], default: "text" },
    ],
  },
  {
    type: "integration.stripe",
    label: "Stripe",
    description: "Process payments and interact with the Stripe API",
    icon: "CreditCard",
    color: "#635bff",
    category: "integrations",
    inputs: 1,
    outputs: 1,
    tags: ["stripe", "payment", "billing", "charge"],
    configSchema: [
      { key: "credential", label: "Stripe Credential", type: "credential", required: true },
      { key: "operation", label: "Operation", type: "select", options: [
        { label: "Create Payment Intent", value: "createPaymentIntent" },
        { label: "Get Customer", value: "getCustomer" },
        { label: "Create Customer", value: "createCustomer" },
        { label: "List Charges", value: "listCharges" },
        { label: "Get Subscription", value: "getSubscription" },
      ], default: "createPaymentIntent" },
    ],
  },
]

export const NODE_CATEGORIES: { id: string; label: string; color: string }[] = [
  { id: "triggers", label: "Triggers", color: "#f97316" },
  { id: "core", label: "Core", color: "#3b82f6" },
  { id: "logic", label: "Logic", color: "#ec4899" },
  { id: "integrations", label: "Integrations", color: "#8b5cf6" },
]

export function getNodeDefinition(type: string): NodeDefinition | undefined {
  return NODE_DEFINITIONS.find((n) => n.type === type)
}

export function getNodesByCategory(category: string): NodeDefinition[] {
  return NODE_DEFINITIONS.filter((n) => n.category === category)
}
